# Generated by Django 4.2.1 on 2023-05-29 13:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom"], name="geom_gist_idx"
            ),
        ),
    ]
